version: "2.0"

# Define the services/containers to be run
services:
  koa-auth-api: # Main API service
    build: . # Directory of dockerfile
    restart: always
    ports:
      - "3000:3000" # Forward required port
    links:
      - database # Link this service to the database service
    volumes:
      - .:/app
    depends_on:
      - database
  database: # Database service
    image: mongo # Specify image to build container from
    ports:
      - "27017:27017"
    volumes:
      - /data/db